apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: midway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midway
  template:
    metadata:
      labels:
        app: midway
    spec:
        containers:
        - name: app-dccn-midway
          image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-midway:feat
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: midway
  labels:
    app: midway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:815280425737:certificate/4c8ad331-4a92-4ae3-85cf-08ed5d95310d
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
  selector:
    app: midway
  type: LoadBalancer