apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: midway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: midway
    spec:
        containers:
        - name: app-dccn-midway
          image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-midway:feat
          imagePullPolicy: Always
          ports:
          - containerPort: 8080